"""Add id_token field to oauth

Revision ID: 85411af31d3b
Revises: 705d70065fbe
Create Date: 2025-01-02 07:33:53.002335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85411af31d3b'
down_revision: Union[str, None] = '705d70065fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth', sa.Column('id_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth', 'id_token')
    # ### end Alembic commands ###
