"""Update oauth model to include expiry and id_token

Revision ID: d7551aaa8313
Revises: 705d70065fbe
Create Date: 2025-01-02 09:14:55.890548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7551aaa8313'
down_revision: Union[str, None] = '705d70065fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth', sa.Column('id_token', sa.String(), nullable=True))
    op.add_column('oauth', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth', 'expires_at')
    op.drop_column('oauth', 'id_token')
    # ### end Alembic commands ###
